on:
  push:
    branches:
      - 'test'

name: 'Deploy TEST instance'
jobs:
  deploy:
    name: 'deployment'
    runs-on:
      labels: 'drupal'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Install dependencies'
        uses: eaudeweb/drupal-install-action@1.x
        with:
          dev: false

      - name: 'Create release archive'
        id: artifact
        uses: eaudeweb/drupal-artifact-action@1.x

      - name: 'Deploy release on the server'
        uses: eaudeweb/drupal-deploy-action@v2.1.4
        with:
          ssh_user:             ${{ secrets.TEST_SSH_USER }}
          ssh_host:             ${{ secrets.TEST_SSH_HOST }}
          ssh_key:              ${{ secrets.TEST_SSH_KEY }}
          release_id:           ${{ steps.artifact.outputs.base }}
          release_filename:     ${{ steps.artifact.outputs.filename }}
          project_dir:          /var/www/html/test.example.org
          artifacts_dir:        /var/www/artifacts/test.example.org
          settings_file:        /var/www/config/test.example.org/settings.local.php
          public_files_dir:     /var/www/config/test.example.org/files
          # env_file:           /var/www/config/test.example.org/.env
          # robo_file:          /var/www/config/test.example.org/robo.yml
          # database_dump_dir:  /var/www/config/test.example.org/sync
          artifacts_lifespan: 30

      - name: 'Update the Drupal instance'
        id: release
        uses: eaudeweb/drupal-update-action@v1
        with:
          path: /var/www/html/test.example.org

      - name: 'Cleanup old releases'
        uses: eaudeweb/drupal-cleanup-action@1.x
        with:
          ssh_user:             ${{ secrets.TEST_SSH_USER }}
          ssh_host:             ${{ secrets.TEST_SSH_HOST }}
          ssh_key:              ${{ secrets.TEST_SSH_KEY }}
          cleanup_dir:          /var/www/artifacts/test.example.org
          retain:               5

      - name: 'Discord notification on failed deploy'
        if: failure()
        run: >
          curl -X POST -F
          "content=:octagonal_sign: **${{ github.repository }}** release **${{ github.ref_name }}** failed to deploy on https://test.example.org/.
          [view action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          ${{ secrets.DISCORD_WEBHOOK }}
